export const defaultQuestions = [
  "Yo nunca nunca me he liado con un/a compañero/a de trabajo o de clase.",
  "Yo nunca nunca he enviado una foto o vídeo íntimo por error a la persona equivocada.",
  "Yo nunca nunca he sido infiel.",
  "Yo nunca nunca he revisado el móvil de mi pareja a escondidas.",
  "Yo nunca nunca me he liado con la ex-pareja de un/a amigo/a.",
  "Yo nunca nunca he fingido un orgasmo.",
  "Yo nunca nunca he hecho un trío.",
  "Yo nunca nunca he mantenido relaciones en un lugar público.",
  "Yo nunca nunca he tenido una fantasía con alguien presente en esta habitación.",
  "Yo nunca nunca he estado en un club de intercambio de parejas o liberal.",
  "Yo nunca nunca he utilizado juguetes íntimos con otras personas.",
  "Yo nunca nunca he grabado un vídeo íntimo.",
  "Yo nunca nunca he tenido un 'lapsus' y he dicho el nombre de mi ex durante el sexo.",
  "Yo nunca nunca he mentido sobre el número de personas con las que me he acostado.",
  "Yo nunca nunca he ghosteado a alguien después de la primera cita porque me dio asco.",
  "Yo nunca nunca he estado enamorado/a de dos personas a la vez.",
  "Yo nunca nunca me he arrepentido al instante de acostarme con alguien.",
  "Yo nunca nunca he practicado sexting en el trabajo o en clase.",
  "Yo nunca nunca me he liado con alguien por despecho.",
  "Yo nunca nunca he dudado de mi orientación sexual.",
  "Yo nunca nunca he hecho algo ilegal estando borracho/a.",
  "Yo nunca nunca he robado algo en una tienda o supermercado.",
  "Yo nunca nunca he mentido en mi currículum para conseguir un trabajo.",
  "Yo nunca nunca he tenido que salir corriendo para que no me pillaran.",
  "Yo nunca nunca he consumido drogas duras.",
  "Yo nunca nunca he roto algo caro y he echado la culpa a otra persona.",
  "Yo nunca nunca me he peleado físicamente con alguien en una fiesta.",
  "Yo nunca nunca he sido detenido/a por la policía.",
  "Yo nunca nunca he espiado a los vecinos mientras hacían algo privado.",
  "Yo nunca nunca he estado con más de dos personas en un margen de 24 horas.",
  "Yo nunca nunca he cobrado o pagado por mantener relaciones sexuales.",
  "Yo nunca nunca he sentido atracción por la madre o el padre de un amigo.",
  "Yo nunca nunca he tenido sexo en la cama de mis padres.",
  "Yo nunca nunca he tenido sexo en un coche aparcado.",
  "Yo nunca nunca he usado Tinder u otra app de citas solo para subirme el ego.",
  "Yo nunca nunca he enviado mensajes subidos de tono estando borracho/a y me he arrepentido al día siguiente.",
  "Yo nunca nunca he tenido un rollo de una noche y no sabía el nombre de la persona.",
  "Yo nunca nunca he tenido fantasías con el/la jefe/a.",
  "Yo nunca nunca he besado a alguien del mismo sexo (si eres hetero) o del sexo opuesto (si eres homo) solo por probar.",
  "Yo nunca nunca he mandado una 'nude'.",
  "Yo nunca nunca he recibido una foto íntima no solicitada y me ha gustado.",
  "Yo nunca nunca he hecho un 'simpa' en un restaurante o bar.",
  "Yo nunca nunca he escupido en la comida o bebida de alguien.",
  "Yo nunca nunca he tenido una ETS (Enfermedad de Transmisión Sexual).",
  "Yo nunca nunca he sido pillado/a masturbándome.",
  "Yo nunca nunca he mantenido una relación secreta durante más de 6 meses.",
  "Yo nunca nunca me he sentido atraído/a por un/a profesor/a.",
  "Yo nunca nunca he hecho un 'walk of shame' (llegar a casa por la mañana con la ropa de fiesta).",
  "Yo nunca nunca he usado la ropa interior de otra persona.",
  "Yo nunca nunca me he bañado desnudo/a en el mar o en una piscina pública."
];
